#ifndef APPINFO
#define APPINFO

#define APPNAME "DySySim"

#define MAJOR_VERSION "0"
#define MINOR_VERSION "8"
#define REVISION_VERSION "0"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif // APPINFO
