#ifndef APPINFO
#define APPINFO

#define APPNAME "TippingFIS"

#define MAJOR_VERSION "0"
#define MINOR_VERSION "3"
#define REVISION_VERSION "7"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif // APPINFO
